services:
  database:
    container_name: "postgres-db"
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: vika
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      DATABASE_URL: jdbc:postgresql://postgres-db:5432/vika
    volumes:
      - ./vika-service-db:/var/lib/vika-service-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command: -p 5432

  coworking-schedule-service:
    build: .
    container_name: "vika-service"
    restart: always
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/vika
      DB_USER: postgres
      DB_PASSWORD: 12345
      DDL_AUTO: create-drop
    ports:
      - "8080:8080"