version: '3.8'
services:
  vika-service:
    container_name: "vika-service"
    image: vika:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DDL_AUTO: ${DDL_AUTO}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}

  service-db:
    container_name: "service-db"
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${PGUSER}
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      command: >
          sh -c "apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8 && docker-entrypoint.sh postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "vika" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - vika-service-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  vika-service-db: